FROM eventhorizontelescope/img-env

COPY eht-imaging/eht-imaging_pipeline.py /usr/local/src/
COPY wrapper.sh /usr/bin

USER jovyan
WORKDIR /img
RUN chmod 755 /usr/bin/wrapper.sh

#WORKDIR /img
ENTRYPOINT ["/usr/bin/wrapper.sh"]
